init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v3.1.0.$env:APPVEYOR_BUILD_NUMBER" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

image: Visual Studio 2019

configuration: Release

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  project: XmlRpcCore.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: false

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
  - nuget restore XmlRpcCore.sln

deploy:
  - provider: NuGet
    name: nuget_release
    api_key:
      secure: MJz3DvmtiuNK6IVsPbxR3gWiSCnhKqm6tmPsjdRDgwGx9L2PQSSZ1eE7YS8dkZhx
    skip_symbols: true
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    name: github_releases
    description: Release v$(appveyor_build_version)
    tag: $(appveyor_build_version)
    auth_token:
      secure: NWduXKOpjxTw6TAgzMV9SsBERjq5Qxv49XKbDtu6XQV7GygeQmG1RTKeyxl4zV1A
    skip_symbols: true
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true